apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.20
        ports:
        - containerPort: 80
          name: http-web-svc
      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "1180"
        - name: HTTPS_PORT
          value: "11443"
        - name: X_PORT
          value: "8080"
        ports:
        - containerPort: 1180
          name: http-port
        - containerPort: 11443
          name: https-port
        - containerPort: 8080
          name: x-port
        resources:
          requests:
            cpu: "1m"
            memory: "20Mi"
          limits:
            cpu: "10m"
            memory: "20Mi"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
