apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
        ports:
        - containerPort: 80
          name: http-web-svc
      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "1180"
        - name: HTTPS_PORT
          value: "11443"
        - name: X_PORT
          value: "8080"
        ports:
        - containerPort: 1180
          name: http-port
        - containerPort: 11443
          name: https-port
        - containerPort: 8080
          name: x-port
        resources:
          requests:
            cpu: "1m"
            memory: "20Mi"
          limits:
            cpu: "10m"
            memory: "20Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: nginx-port
    protocol: TCP
    port: 9001
    targetPort: http-web-svc
  - name: multitool-port-http
    protocol: TCP
    port: 1180
    targetPort: http-port
  - name: multitool-port-https
    protocol: TCP
    port: 11443
    targetPort: https-port
  - name: multitool
    protocol: TCP
    port: 9002
    targetPort: x-port
